// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCut4c3neG7-Y0QaIhrvwY9f7taWGoQhyA',
    appId: '1:433609609754:web:fadf189bda3ad55240b7a3',
    messagingSenderId: '433609609754',
    projectId: 'school-community-f8e5c',
    authDomain: 'school-community-f8e5c.firebaseapp.com',
    storageBucket: 'school-community-f8e5c.appspot.com',
    measurementId: 'G-YKY1JBV5PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrzWTeRD5hAQw1bQRc-D2dIMm6DaxO6o',
    appId: '1:433609609754:android:e9b4c74d1fc09f6b40b7a3',
    messagingSenderId: '433609609754',
    projectId: 'school-community-f8e5c',
    storageBucket: 'school-community-f8e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUr5sFiJ-UZxCwiWj-qXjLXXIxw7PIjBI',
    appId: '1:433609609754:ios:42a67320d024dbe240b7a3',
    messagingSenderId: '433609609754',
    projectId: 'school-community-f8e5c',
    storageBucket: 'school-community-f8e5c.appspot.com',
    iosBundleId: 'com.example.sustApp',
  );
}
